config/routes.rb
Rails.application.routes.draw do
  resources :dropoffs
  resources :pickups
  resources :trips
  resources :schedules
  resources :dogs
  resource :sessions
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/dog.rb
class Dog < ApplicationRecord
  has_many :pickups

  validates :name, presence: true

  def trip_for_today
    Trip.where(date: Date.current).detect { |trip|
      trip.dogs.include?(self)
    }
  end

  def weekly_schedule
    Date::DAYNAMES[1..-2].select { attribute(_1) }
  end

  def status
    trip = trip_for_today
    return "At Home" unless trip

    pickup = trip.pickups.find_by(dog: self)
    dropoff = trip.dropoffs.find_by(dog: self)

    case
    when dropoff       then "Dropped Off"
    when trip.departed then "Departed"
    when trip.arrived  then "Arrived"
    when pickup        then "Picked Up"
    else                    "At Home"
    end
  end
end

app/models/dropoff.rb
class Dropoff < ApplicationRecord
  belongs_to :dog
  belongs_to :trip
end

app/models/pickup.rb
class Pickup < ApplicationRecord
  belongs_to :dog, required: true
  belongs_to :trip, required: true
end

app/models/schedule.rb
class Schedule < ApplicationRecord
  has_many :trips, foreign_key: :date
  validates :date, presence: true

  before_save do
    write_attribute(:raw_assignments, assignments.to_json)
  end

  def name
    date.strftime("%A")
  end

  def assignments
    @assignments ||= JSON.parse(raw_assignments)
  end

  def assignments=(hash)
    @assignments = hash.compact
  end

  def dogs
    assignments.keys
  end

  def trucks
    assignments.values.uniq
  end

  def truck_assignments
    assignments.reduce(Hash.new { |h, k| h[k] = [] }) { |agg, (dog_id, truck_id)| agg.tap { |a|  a[truck_id] << dog_id } }
  end
end

app/models/trip.rb
class Trip < ApplicationRecord
  belongs_to :schedule, primary_key: :date, foreign_key: :date
  has_many :pickups
  has_many :dropoffs

  delegate :truck_assignments, to: :schedule

  def dogs
    Dog.find(schedule.truck_assignments[truck_id.to_s])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern

  before_action :set_role

  def set_role
    @role = session[:role_name]
  end

  def dashboard
    case session[:role_name]
    when "Manager"
      redirect_to dogs_path
    when "Walker"
      redirect_to trips_path
    else
      flash[:error] = "Missing Role"
      redirect_to new_sessions_path
    end
  end
end

app/controllers/dogs_controller.rb
class DogsController < ApplicationController
  def index
    @dogs = Dog.all
  end

  def new
    @dog = Dog.new
  end

  def edit
    @dog = Dog.find(params[:id])
  end

  def update
    dog = Dog.find(params[:id])
    if dog.update(attr_params)
      redirect_to dogs_path
    else
      flash[:error] = dog.errors.full_messages

      render :new
    end
  end

  def create
    @dog = Dog.new(attr_params)
    if @dog.save
      redirect_to dogs_path
    else
      flash[:error] = @dog.errors.full_messages

      render :new
    end
  end

  def attr_params
    params.fetch(:dog, {}).permit(
      :name,
      :Monday,
      :Tuesday,
      :Wednesday,
      :Thursday,
      :Friday,
    )
  end
end

app/controllers/dropoffs_controller.rb
class DropoffsController < ApplicationController
  def create
    dropoff = Dropoff.create!(attr_params)
    redirect_to edit_trip_path(dropoff.trip)
  end

  def attr_params
    params.fetch(:dropoff, {}).permit(:dog_id, :trip_id)
  end
end

app/controllers/pickups_controller.rb
class PickupsController < ApplicationController
  def create
    pickup = Pickup.create!(attr_params)
    redirect_to edit_trip_path(pickup.trip)
  end

  def attr_params
    params.fetch(:pickup, {}).permit(:dog_id, :trip_id)
  end
end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController
  def index
    @schedules = Schedule.all
  end

  def new
    @schedule = Schedule.new(attr_params)
  end

  def create
    @schedule = Schedule.new(attr_params)
    if @schedule.save
      redirect_to edit_schedule_path(@schedule)
    else
      flash[:errors] = @schedule.errors.full_messages
      render :new
    end
  end

  Truck = Struct.new(:id, keyword_init: true)

  def edit
    @schedule = Schedule.find(params[:id])
    @trucks = (1..3).map { Truck.new(id: _1) }

    day = @schedule.date.strftime("%A")
    @dogs = Dog.where(day => true)
  end

  def update
    @schedule = Schedule.find(params[:id])
    if @schedule.update(attr_params)
      redirect_to schedules_path
    else
      flash[:errors] = @schedule.errors.full_messages
      render :new
    end
  end

  private
    def attr_params
      params.fetch(:schedule, {}).then { |p|
        p.permit(
          :date,
          assignments: p.dig(:assignments)&.keys
        )
      }
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    session[:role_name]=params[:role]
    dashboard
  end

  def destroy
    session.clear
    redirect_to new_sessions_path
  end
end

app/controllers/trips_controller.rb
class TripsController < ApplicationController
  def new
    @trip = Trip.new(date: Date.current)
  end

  def create
    @trip = Trip.new(attr_params)
    @trip.save!
    redirect_to edit_trip_path(@trip)
  end

  def edit
    @trip = Trip.find(params[:id])
  end

  def update
    @trip = Trip.find(params[:id])
    @trip.update!(attr_params)
    redirect_to edit_trip_path(@trip)
  end

  private

    def attr_params
      params.fetch(:trip, {}).permit(:date, :truck_id, :arrived, :departed).tap {|p|
        case params[:commit]
        when 'Arrived'
          p[:arrived] = true
        when 'Departed'
          p[:departed] = true
        end
      }
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_navigation_bar.html.slim
header.header
  div.grid
    h1 Doggo
    = button_to 'Logout', sessions_path, method: :delete
.navbar.grid
  - if @role == "Manager"
    = link_to 'Scheduling', schedules_path, class: (controller_name=='schedules' ? 'active' : nil)
    = link_to 'Dogs', dogs_path, class: (controller_name=='dogs' ? 'active' : nil)
  - elsif @role == "Walker"
    = link_to 'Trips', trips_path
  pre
    |     __         //
      o──*()`───────//
       "~\    __    _/
          (_(_) (_(_)

app/views/dogs/_form.html.slim
= form_with model: @dog do |form|
  = form.label :name
  = form.text_field :name
  
  - Date::DAYNAMES[1..-2].each do |weekday|
    = form.label weekday
    = form.check_box weekday
  hr
  = form.submit 'Save'

app/views/dogs/edit.html.slim
= render "form"

app/views/dogs/index.html.slim
= link_to 'Add Dog', new_dog_path

table
  tr
    th Name
    th Weekly Schedule
    th Currently
  - @dogs.each do |dog|
    tr
      td = link_to(dog.name, edit_dog_path(dog))
      td = dog.weekly_schedule.map{ _1[0..2] }.join(",")
      td = dog.status

app/views/dogs/new.html.slim
= form_with model: @dog do |form|
  = form.label :name
  = form.text_field :name
  
  - Date::DAYNAMES[1..-2].each do |weekday|
    = form.label weekday
    = form.check_box weekday

  = form.submit 'Save'

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Doggo" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'navigation_bar' %>
    <% flash.each do |type, msg| %>
      <div>
        <%= msg %>
      </div>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/schedules/edit.html.slim
= form_with model: @schedule do |form|
  = form.label :date
  = form.date_field :date
  br
  
  = form.fields_for :assignments do |assignments_form|
    - @dogs.each do |dog|
      br
      .dog
        = assignments_form.label dog.id, "#{dog.name} Truck Assignment"
        = assignments_form.text_field dog.id, value: @schedule.assignments[dog.id.to_s]
  hr
  = form.submit 'Save'

app/views/schedules/index.html.slim
= link_to 'New Daily Schedule', new_schedule_path

table
  tr
    th Date
    th Day Name
    th Dog Count
    th Truck Count
  - @schedules.each do |day|
    tr
      td = link_to day.date, edit_schedule_path(day)
      td = link_to day.name, edit_schedule_path(day)
      td = day.dogs.count
      td = day.trucks.count

app/views/schedules/new.html.slim
= form_with model: @schedule do |form|
  = form.label :date
  = form.date_field :date
  br
  = form.submit 'Schedule Dogs'

app/views/trips/edit.html.slim
h2 = @trip.schedule.name
hr
.dogs
  - @trip.dogs.each do |dog|
    - case dog.status
    - when 'At Home'
      = form_with model: @trip.pickups.new do |form|
        = form.hidden_field :dog_id, value: dog.id
        = form.hidden_field :trip_id, value: @trip.id
        = form.submit("#{dog.name} Picked Up")
    - when "Departed"
      = form_with model: @trip.dropoffs.new do |form|
        = form.hidden_field :dog_id, value: dog.id
        = form.hidden_field :trip_id, value: @trip.id
        = form.submit("#{dog.name} Dropped Off")
hr

= form_with model: @trip do |form|
  = form.hidden_field :arrived
  = form.hidden_field :departed

  - if @trip.departed
  - elsif @trip.arrived
    = form.submit 'Departed'
  - else
    = form.submit 'Arrived'

app/views/trips/index.html.slim
= link_to "Start Today", new_trip_path

app/views/trips/new.html.slim
= form_with model: @trip do |form|
  div.grid
    div
    div
      p = "Today is #{@trip.date}."
      p = "Please choose a truck."
      = form.hidden_field :date
      = form.select :truck_id, @trip.schedule.trucks.map { ["Truck #{_1}", _1] }
      br
      = form.submit 'Go'
    div